version: '2'

services:
  curator:
    image: robinaa/elasticsearch-curator-docker:latest
    external_links:
      - elasticsearch:elasticsearch
    volumes:
      - $PWD/action_file.yml:/etc/curator/action_file.yml
      - $PWD/config.yml:/etc/curator/config.yml
    environment:
      - SCHEDULE=30 23 * * *
      - COMMAND=curator --config /etc/curator/config.yml  /etc/curator/action_file.yml
    networks:
      - logging

networks:
  logging:
    external: true
